@startuml
客户端 -> 存储服务器1 : 1. 只从正常服务器读取数据
...
客户端 -> 存储服务器1 : 2. 写入数据到正常服务器
客户端 -> 临时故障恢复状态存储服务器2 : 3. 写入数据到临时故障恢复状态的存储服务器
...
临时服务器 -> 临时故障恢复状态存储服务器2 : 4. 从临时服务器迁移故障期间写入的数据
...
管理中心 -> 客户端 : 5. 迁移完成后管理中心通知所有客户端，临时故障恢复状态存储服务器2恢复为正常状态
...
客户端 -> 存储服务器1 : 6. 从存储服务器1, 读取和写入数据
客户端 -> 临时故障恢复状态存储服务器2 : 7. 从存储服务器2, 读取和写入数据
@enduml