@startuml
客户端 -> 存储服务器 : 1. 请求服务
客户端 <-- 存储服务器 : 2. 通讯超时,不可识别异常
...
客户端 -> 存储服务器 : 3. 重新请求(x 次)
客户端 <-- 存储服务器 : 4. 通讯超时，不可识别异常
...
客户端 -> 管理中心 : 5. 存储服务器失效仲裁请求
...
管理中心 -> 存储服务器 : 6. 发送心跳检测、失效仲裁检测(重试 x 次)
存储服务器 --> 管理中心 : 7. 通讯超时，不可识别异常
...
管理中心 -> 客户端 : 8. 标记这台存储服务器为临时失效状态，同时通知所有客户端，存储服务器失效


@enduml