@startuml
客户端 -> 存储服务器2 : 1. 读数据(只从正常服务器读取数据)
...
客户端 -> 存储服务器2 : 2. 写入数据
客户端 -> 临时服务器 : 3. 故障服务器恢复服务前，写入数据
...
故障存储服务器1 <- 临时服务器 : 4. 故障服务器恢复服务后，从临时服务器迁移故障期间写入的数据
...
管理中心 -> 客户端 : 5. 通知所有客户端故障服务器1恢复
...
客户端 -> 故障存储服务器1 : 6. 迁移完成，恢复正常写入
客户端 -> 存储服务器2 : 7. 迁移完成，恢复正常写入
@enduml