@startuml
header 扣款流程
金额管理 -> 数据库 : 1. 根据卡片id查询余额
数据库 -> 金额管理 : 2. 返回余额
金额管理 -> 数据库 : 3. 如果余额 >= 本次扣款额，则将 余额-本次充值金额 更新到数据库，否则提示扣款失败
金额管理 -> 消费记录 : 4. 如果扣款成功，则记录本次消费
消费记录 -> 数据库 : 5. 将本次消费记录到数据库中
@enduml