@startuml
消费者 -> 访问代理: 调用服务接口
访问代理 -> dubbo客户端: 调用 dubbo 客户端
dubbo客户端 -> 注册中心: 从远程获取服务列表，并缓存到本地
注册中心 --> dubbo客户端: 服务列表
dubbo客户端 -> dubbo客户端: 从本地获取服务列表
dubbo客户端 -> 服务端服务调用线程: 发起远程调用
服务端服务调用线程 -> 服务提供者: 调用服务接口
服务提供者 --> 服务端服务调用线程: 返回数据
服务端服务调用线程 --> dubbo客户端: 返回数据
dubbo客户端 --> 访问代理: 返回数据
访问代理 --> 消费者: 返回数据
@enduml